PROJECT_NAME = 'FACE MASK DETECTION SYSTEM'
DONE_BY = 'BY : HARENDRA PRAJAPATI'
PRESS1 = 'PRESS TO KNOW ABOUT'
PRESS2 = 'PRESS FOR INSTRUCTION'
PRESS3 = 'PRESS TO SEE DATASET SAMPLE'
PRESS4 = 'PRESS FOR VIDEO BASED TEST'
PRESS5 = 'PRESS FOR CAMERA BASED TEST'
MENU_OPTION = ('About project','Instruction to use','Sample dataset','realtime detection','image based test')